json.array!(@v_devolucion) do |v_devolucion|
  json.extract! v_devolucion, :id, :ID_DEVOLUCION, :ID_VENTA, :ID_LOCAL, :ID_VENDEDOR, :ID_ESTADO_DEVOLUCION, :FECHA_DEVOLUCION, :MONTO_CAMBIO, :CANT_INSUMOS_NUEVOS_DEVOLUCION, :TIPO_DEVOLUCION, :COMENTARIO_DEVOLUCION, :INSUMOS_DEFECTUOSOS_DEVOLUCION, :NOMBRE_VENDEDOR, :NOMBRE_CLIENTE, :ESTADO_ACTUAL, :DIRECCION_LOCAL
  json.url v_devolucion_url(v_devolucion, format: :json)
end
